name: Test, Publish, & Release

on:
  push:
    tags:
      - v*.*.*
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn
      - run: |
          echo @dancrumb:https://npm.pkg.github.com/ > .npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> .npmrc
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create-release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ncipollo/release-action@v1
